
DEF GROUND_LEVEL        EQU 144

; Score
DEF SCORE_LAST_POSITION EQU $980C
DEF SCORE_SIZE          EQU 8

; HP
DEF HP_POSITION         EQU $9800

; Sprites
DEF PLAYER_SPRITE_TILE  EQU $00
DEF CAT_SPRITE_TILE     EQU $04
DEF CAT_SPRITE_TILE2    EQU $06
DEF PIGEON_SPRITE_TILE  EQU $08
DEF P_MISSILE_SPRITE    EQU $0A
DEF P_MISSILE_SPRITE2   EQU $0C
DEF SOMSIAD_SPRITE      EQU $0E

; Tiles
DEF TILE_FONT_0         EQU $80
DEF TILE_FONT_1         EQU $81
DEF TILE_BACKGROUND     EQU $00
DEF TILE_HEAD           EQU $3D

; Player
DEF PLAYER_MAX_LEFT     EQU 0
DEF PLAYER_MAX_RIGHT    EQU 144
DEF PLAYER_START_HP     EQU 5

; Cat
DEF CATS_MAX_LEFT       EQU 16 + 8
DEF CATS_MAX_RIGHT      EQU 136 + 8
DEF CATS_BASE_SPEED     EQU 1
DEF CATS_MAX_COUNT      EQU 5
DEF CATS_SPAWN_DELAY    EQU 50

; Cat struct
rsreset
DEF cat_active          RB 1
DEF cat_x_pos           RB 1
DEF cat_y_pos           RB 1
DEF CAT_BYTES_COUNT     RB 0

; Pigeon
DEF PIGEON_CURRENT_Y EQU 8
DEF PIGEON_SHIT_MAX_COUNT EQU 2
DEF PIGEON_SHIT_SPAWN_DELEY EQU 55
DEF PIGEON_SHIT_MAX_SPEED EQU 1

; Pigeon missile struct
rsreset
DEF p_missile_active                RB 1
DEF p_missile_x_pos                 RB 1
DEF p_missile_y_pos                 RB 1
DEF PER_PIGEON_MISSILE_BYTE_COUNT   RB 0

; Somsiad
DEF SOMSIAD_ANIMATION_DELEY EQU 66
DEF SOMSIAD_X_POS           EQU 24
DEF SOMSIAD_Y_POS           EQU 58
